# Generated by Django 3.0.6 on 2020-06-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('store_time', models.CharField(max_length=100)),
                ('map_url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'stores',
            },
        ),
    ]
