# Generated by Django 3.0.6 on 2020-06-01 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_policy', models.CharField(max_length=2000)),
                ('customer_service', models.CharField(max_length=2000)),
                ('expiration', models.CharField(max_length=100)),
                ('quality_assurance', models.CharField(max_length=2000)),
                ('main_spec', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'basic_informations',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category')),
            ],
            options={
                'db_table': 'categories_products',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image_url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='ColorProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField(default=0)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Color')),
            ],
            options={
                'db_table': 'colors_products',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'manufacturers',
            },
        ),
        migrations.CreateModel(
            name='ManufacturerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Manufacturer')),
            ],
            options={
                'db_table': 'manufacturers_products',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_krw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=100)),
                ('launch_date', models.DateField()),
                ('caution', models.CharField(max_length=3000)),
                ('volume_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mfds', models.CharField(max_length=300)),
                ('how_to_use', models.CharField(max_length=500)),
                ('is_limited', models.BooleanField(default=False)),
                ('inner_image_url', models.URLField(max_length=2000)),
                ('outer_front_image_url', models.URLField(max_length=2000)),
                ('outer_back_image_url', models.URLField(max_length=2000)),
                ('basic_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.BasicInformation')),
                ('category', models.ManyToManyField(related_name='categories', through='product.CategoryProduct', to='product.Category')),
                ('color', models.ManyToManyField(related_name='colors', through='product.ColorProduct', to='product.Color')),
                ('manufacturer', models.ManyToManyField(related_name='manufacturers', through='product.ManufacturerProduct', to='product.Manufacturer')),
                ('shipping_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.ShippingInformation')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AddField(
            model_name='manufacturerproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AddField(
            model_name='colorproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
    ]
