# Generated by Django 3.0.6 on 2020-05-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorproduct',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='basicinformation',
            table='basic_informations',
        ),
        migrations.AlterModelTable(
            name='manufacturer',
            table='manufacturers',
        ),
    ]
