# Generated by Django 3.0.6 on 2020-06-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_shipping_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(through='product.CategoryProduct', to='product.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ManyToManyField(through='product.ManufacturerProduct', to='product.Manufacturer'),
        ),
    ]
