# Generated by Django 3.0.6 on 2020-05-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderdetail',
            table='order_details',
        ),
        migrations.AlterModelTable(
            name='orderstatus',
            table='order_status',
        ),
        migrations.AlterModelTable(
            name='paymentmethod',
            table='payment_methods',
        ),
        migrations.AlterModelTable(
            name='shippinginformation',
            table='shipping_information',
        ),
    ]
